# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-16 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='undefined'),
        ),
    ]
