# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-19 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180719_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/static/img', verbose_name='Image'),
        ),
    ]
